soundcloud:
  client_id: 3c0cc5b1a12f1f96632540f8bd115218
  client_secret: 24a2e9c8073b69c943b9c5c0c41d8a98

amazon:
  access_key_id: AKIAJ7OELDJ7IEEYO2KQ
  secret_access_key: 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