soundcloud:
  client_id: 0e68476bc275742ff07f39f1e334113e
  client_secret: 09d7efb0166175861e3d94ab4918c5ad

amazon:
  access_key_id: AKIAICLV2E2IHREGFEIA
  secret_access_key: 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